export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_RECORDS_SUCCESS = 'LOAD_RECORDS_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_RECORD_SUCCESS = 'CREATE_RECORD_SUCCESS';
export const UPDATE_RECORD_SUCCESS = 'UPDATE_RECORD_SUCCESS';
